In [25]:
import numpy as np
import pandas as pd

# Stock A price data (5 days × 3 features: Open, High, Low)
stock_A = np.array([
    [120, 121, 122],
    [102, 188, 171],
    [104, 124, 103],
    [103, 159, 100],
    [105, 131, 104]
])

# Stock B price data (5 days × 3 features: Open, High, Low)
stock_B = np.array([
    [98, 104, 97],
    [101, 107, 100],
    [103, 119, 102],
    [102, 108, 99],
    [105, 110, 100]
])

# Convert to DataFrame for better visualization
df_A = pd.DataFrame(stock_A, columns=["Open", "High", "Low"])
df_B = pd.DataFrame(stock_B, columns=["Open", "High", "Low"])

print("Stock A Data:\n", df_A)
print("\nStock B Data:\n", df_B)

# Element-wise Sum
sum_matrix = stock_A + stock_B

# Element-wise Difference
diff_matrix = stock_A - stock_B

print("\nElement-wise Sum of Stock Prices:")
print(sum_matrix)

print("\nElement-wise Difference of Stock Prices:")
print(diff_matrix)

Stock A Data:
    Open  High  Low
0   120   121  122
1   102   188  171
2   104   124  103
3   103   159  100
4   105   131  104

Stock B Data:
    Open  High  Low
0    98   104   97
1   101   107  100
2   103   119  102
3   102   108   99
4   105   110  100

Element-wise Sum of Stock Prices:
[[218 225 219]
 [203 295 271]
 [207 243 205]
 [205 267 199]
 [210 241 204]]

Element-wise Difference of Stock Prices:
[[22 17 25]
 [ 1 81 71]
 [ 1  5  1]
 [ 1 51  1]
 [ 0 21  4]]
