In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [10]:
#index where the values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [12]:
arr=np.array([3,2,0,1])
print("\nOriginal array",arr)
print("\nSorted array",np.sort(arr))
arr=np.array([[3,2,4],[5,0,2]])
print("\nOriginal array",arr)
print("\nSorted array",np.sort(arr))


Original array [3 2 0 1]

Sorted array [0 1 2 3]

Original array [[3 2 4]
 [5 0 2]]

Sorted array [[2 3 4]
 [0 2 5]]


In [7]:
#filter
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [9]:
arr=np.array([41,42,43,44])
filterarr=arr>42
newarr=arr[filterarr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:",filterarr)
print("\nNew array:",newarr)


Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]

New array: [43 44]
