In [2]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created :\n",a)

Array created :
 [[1 2 4]
 [5 8 7]]


In [3]:
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
c=np.full((3,3),6)
print("Array with all 6s :\n",c)

Array with all 6s :
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [9]:
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.14671159 0.74552201]
 [0.18554149 0.25626217]]


In [16]:
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [19]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\n Original array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [20]:
flarr=arr.flatten()
print("\n original array:\n",arr)
print("\n flattened array:\n",flarr)


 original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [29]:
flarr=arr.flatten()
print("\n orginal:\n",arr)
print("\n flattened array:\n",flarr)
import numpy as np
arr=np.array([[1,2,3,4],[5,4,3,7],[6,7,0,1]])
print("\n No of dimensions:\n",arr.ndim)
print("\n shpe of array:\n",arr.shape)
print("\n Sixe of array:\n",arr.size)
print("\n Array type:\n",arr.dtype)
newtype=arr.astype('f')
print("\n converted array element:\n",newtype.dtype)
print("\n converted array type:\n",newtype.dtype)


 orginal:
 [[1 2 3 4]
 [5 4 3 7]
 [6 7 0 1]]

 flattened array:
 [1 2 3 4 5 4 3 7 6 7 0 1]

 No of dimensions:
 2

 shpe of array:
 (3, 4)

 Sixe of array:
 12

 Array type:
 int32

 converted array element:
 float32

 converted array type:
 float32


In [33]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:3:])
print(p[:1,])
c=p.astype('f')
print(c)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[[1 2 3]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
